### ISSUE TITLE
Could you please post an environment specification? Such as requirements.txt?

### ISSUE THREAD

**Issue by zzxn** [code-gen/cscg#2]
Hi, I ran into some troubles with libs this code uses.
For now, my notebook complains that it cannot find `bagoftools.config` which I try to install with `pip install bagoftools`, but I have no idea if this is appropriate version. The error message is:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-13dfe3210d77> in <module>
     20 from language_model.lm_prob import LMProb
     21 
---> 22 from bagoftools.config import Config
     23 
     24 from torch.utils.tensorboard import SummaryWriter

ModuleNotFoundError: No module named 'bagoftools.config'
```

And **Could you please post an environment specification? Such as requirements.txt?**

**Comment by alexandru-dinu** [comment]
Hello!

Sorry for the trouble. 

[`bagoftools`](https://github.com/alexandru-dinu/bagoftools) is a Python package I implemented in order to simplify config management. The `Config` class is now [`Namespace`](https://github.com/alexandru-dinu/bagoftools/blob/master/bagoftools/namespace.py). If you don't want to install this package, you can simply get the `namespace.py` file and put it in the working directory.

I fixed & updated some imports, and added a [requirements.txt](https://github.com/code-gen/cscg/blob/master/requirements.txt). Please pull the latest changes (this linked commit) and let me know if there are any other problems.

All the best,
Alex
